theme: jekyll-theme-leap-day
title: Trial for MMS142
description: Created for practice
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Report
    url: report
  - title: Members' Page
    url: memberslist
